### ISSUE TITLE
Jupyter kernel crashing during fit

### ISSUE THREAD

**Issue by davidgwyrick** [lindermanlab/ssm#116]
I'm not sure if it's the way i've installed the package, but for some reason I can't even run a simply gaussian HMM without the kernel crashing. It only throws me this error: 

OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Any ideas ? Is there an established way of creating a conda environment with ssm instead of pip and virtualenv?

**Comment by davidgwyrick** [comment]
Looks like there's a Segmentation Fault (core dumped) error somewhere. I'm not sure why this deprecation error is being thrown anyway because I installed ssm without OpenMP parallel support...

**Comment by slinderman** [comment]
Hey David, sorry, not sure what's causing that!  We've mostly removed cython from the master branch of SSM (and the refactor we're working on will switch entirely to JAX).  The only remaining cython is [cstats.pyx](https://github.com/lindermanlab/ssm/blob/master/ssm/cstats.pyx), and there's only one instance of `prange` in there.  What's strange is that this code should never even be hit unless you're fitting a multivariate-t HMM.   Perhaps you can try stripping out OMP altogether by replacing the `prange` with `range` and removing the import from `cstats.pyx`.  Then make sure to recompile without the `USE_OPENMP` flag.  While you're at it, start with a fresh clone of `ssm` to ensure you don't have any old `.so` files lying around.

**Comment by davidgwyrick** [comment]
Thank you for the quick reply scott. I did a fresh clone of the git repo, created a new conda environment, and that seemed to work. I always seem to find weird bugs in fresh installs!

**Comment by slinderman** [comment]
Great!  I'll go ahead and close this then!
