### ISSUE TITLE
Constraining C during PLDS model fitting

### ISSUE THREAD

**Issue by erinshappell** [lindermanlab/ssm#135]
I'm interested in fitting a PLDS model with partial constraints on C--is there a way to achieve this using SSM? If not, could this be achieved by setting priors on the observation matrix (and if so, where should I look to set those priors)? Thanks!

**Comment by slinderman** [comment]
Hi Erin, that's certainly possible but it would involve a little code modification. Do you want to fix the other emissions parameters (i.e. the input weights, bias, and covariance matrix) too? If so, a simple thing to do is set the emissions model `m_step` to a no-op:
```
slds.emissions.m_step = lambda *args, **kwargs: None
```
