### ISSUE TITLE
Can input driven transitions and observations be combined?

### ISSUE THREAD

**Issue by dbdorman** [lindermanlab/ssm#138]
Thanks for the great repository & related publication! I'm interested in combining input driven transitions and input driven observations (similar to the model in Calhoun, A. J., Pillow, J. W., & Murthy, M. (2019). Unsupervised identification of the internal states that shape natural behavior. Nature Neuroscience, 22(12), 2040–2049. https://doi.org/10.1038/s41593-019-0533-x)

I see that both features are available independently in this repository. Can they be combined in a straightforward way, or are there potential issues I would encounter with model fitting in that case? @zashwood I found your biorxiv paper ("Mice alternate between discrete strategies during perceptual decision-making" very interesting and thought you might readily have an answer for my question. Thanks!

**Comment by zashwood** [comment]
Hi @dbdorman Great question!  I believe that you should be able to combine both classes in the straightforward way.  One issue that I foresee is that, by combining these classes, you add a significant number of parameters to the GLM-HMM with the stationary transition matrix, so after fitting the model with both input-driven transitions and observations, I would make sure that you can retrieve the fit parameters in simulation.
