### ISSUE TITLE
ARHMM usage

### ISSUE THREAD

**Issue by shreyask3107** [lindermanlab/ssm#154]
Hello @slinderman , could you let me know how I could use an ARHMM model to fit my data? 
I could only find the HMM class object defined in this code.

Thanks!

**Comment by slinderman** [comment]
Hi Shreyas,

Why don't you try our new JAX based library, dynamax. We have an [ARHMM example](https://probml.github.io/dynamax/notebooks/hmm/autoregressive_hmm.html) in the documentation.
